version: '3.3'
# es la versión de yml

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=rafa
      - POSTGRES_PASSWORD=1212

    ports:
    - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@email.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - 5050:80

  mysql:
    image: mysql:5432
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1212
      - MYSQL_PORT=3306

      ports:
        -3306:3306
      volumes:
        - ./postgres_data:/var/lib/mysql

    phpmyadmin: