version: '3.3'
# es la versión de yml

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=rafa
      - POSTGRES_PASSWORD=1212

    ports:
    - 6543:6543
    volumes:
    - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@email.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - 5050:80